### ISSUE TITLE
This Isn't The Latest Build As Shown On The Main Thread

### ISSUE THREAD

**Issue by jredfox** [BenDonnelly/Arcticraft#1]
It's been 4 freaken years just release the latest version that we saw in the videos I can even fix some coding errors as I have done with your "just crap". It is that because it's not the latest version shown on the thread because, the biomes are soooo different and the textures of the leaves are different as well as there isn't a yeti.

For Example: have the same mobs/items/blocks you had hear
https://www.youtube.com/user/ArcticraftDEV/videos

Have the same great biome and textures you had here:
http://imgur.com/a/KDyNO

It's not hard I already compiled this and played it some. I was highly disappointing as it looked nothing like the updated textures and biome on the thread from 4 years ago and it took me a year to learn java. A year to find out that this respiratory wasn't the one as advertised.  I just simply deleted your broken main menu glass and commented out some code. 

Sorry if I sounded rude but, yeah I would love to have the biome seen in the picture not the current flat frosty forest and the features which seemed to have disappeared.  I even looked with the wayback machine and finally found the old site tonight and there wasn't a download there either.

**Comment by BenDonnelly** [comment]
Hello,

Arcticraft was a failed project, plain and simple. Yes the version on GitHub won't be the one I have on my desktop somewhere I think, there were many different versions of it, with various degrees of completion.

The ones advertised on YouTube and the forum was the BEST version of Arcticraft, but we never got it completed and I didn't want to release a unfinished project. As far as I'm aware, Minecraft Modding isn't really popular anymore, and the game itself is dying? But I could be wrong.

As far as your request, I'm not going to go look through hundreds of files to try and find the version of Arcticraft we advertised. Sorry. 

Ben

**Comment by jredfox** [comment]
How does this sound make a **google drive/ Mediafire and upload all sources** and I will compile and go through each ones searching for the one with the good biomes, then I will combine it with the latest one with music.

**I will be willing to spend over a hundred hours doing this for you so please let me. I will even update it to 1.10.2  but, I also need the updated core as well if you ever updated them. So I guess first upload all arcticraft versions then upload 3-5 versions of the core you have thanks greatly appreciated**

**Comment by BenDonnelly** [comment]
It's not as simple as that. The reason you're seeing shitty biomes will be because we would have been tweaking them. To be completely honest, versioning of Arcticraft was horrible, and there is loose code all over. Sure I could give you a bunch of code but I don't think you could actually compile it in into the version from YouTube. 

The only thing I can think of is there was a pre-release build we gave TheAtlanticCraft before, if I can find that I will give you it, that is probably one of the better versions.

At work currently, will do it tonight (UK Time)

**Comment by jredfox** [comment]
Ok thanks. You underestimate me though as I am a modder of silk spawners and am starting to learn asm. If necessary I will buy your hardrive, your old pc whatever it takes.

I got a plan to go through all of the biomes after each one is compiled and run it. The one on the main thread looks amazing the best biome I have ever seen.  So yes I would love the one from Atlanticraft gave you but, please don't let this die I am offering to take the best out of the worst and work on getting to what was advertised in the videos. Send me everything thanks. I will keep the dev hidden from the public until I get to the advertised videos by working on a messed up workspace then I will say unstable beta builds. Doesn't even compile.

**Comment by BenDonnelly** [comment]
Hm, email me if you need more info or have further questions. Bendonnelly4@gmail.com
